### ISSUE TITLE
Stackoverflow Exception When Saving

### ISSUE THREAD

**Issue by mattiascibien** [timheuer/taglib-sharp-portable#5]
Hello,
I am currently writing a Windows Store (and Phone 8.1) app using your Taglib-Sharp fork. I create the File object using:

                var fileStream = await _tagFileService.File.OpenAsync(FileAccessMode.ReadWrite);
                file = TagLib.File.Create(new StreamFileAbstraction(_tagFileService.File.Name, fileStream.AsStream(), fileStream.AsStream()));
                Tags = file.GetTag(TagTypes.Id3v2);

Then i call file.Save() after modifying it and I get a stackoverflow exception.

**Comment by pvolchek** [comment]
The following code in File.cs may give us some hints.

```
		public AccessMode Mode {
			get {return (file_stream == null) ?
				AccessMode.Closed : (file_stream.CanWrite) ?
					AccessMode.Write : AccessMode.Read;}
			set {
				if (Mode == value || (Mode == AccessMode.Write
					&& value == AccessMode.Read))
					return;
				
				if (file_stream != null)
					file_abstraction.CloseStream (file_stream);
				
				file_stream = null;
				
				if (value == AccessMode.Read)
					file_stream = file_abstraction.ReadStream;
				else if (value == AccessMode.Write)
					file_stream = file_abstraction.WriteStream;
				
				Mode = value;
			}
		}
```

First of all, note that last line is a recursive call, which is causing `Process is terminated due to StackOverflowException` exception under certain scenarios.

Also notice the call to close the stream. So, if you implement Close() on a stream in your abstraction, then you'll probably end up with `System.ObjectDisposedException: Cannot access a closed file.`

**Comment by RafaelYousuf** [comment]
Any updates on how to resolve this issue? Currently have the same problem in my WinRT app.

**Comment by RafaelYousuf** [comment]
Managed to fix the issue, would like to push the fix to the repo but VS gives me HTTP Error 403 (Forbidden).

**Comment by mattiascibien** [comment]
@RafaelYousuf you first need to [fork the repo](https://github.com/timheuer/taglib-sharp-portable/issues/5#fork-destination-box) and then do the modifications in your fork.

After that you must create a pull request to be reviewed by the original author. 

Have a nice day.

**Comment by RafaelYousuf** [comment]
@mattiascibien thnx for the instructions. I pushed the changes to the repo.

**Comment by mattiascibien** [comment]
@RafaelYousuf  Nice work... :+1:

**Comment by RafaelYousuf** [comment]
@mattiascibien thank you.
